/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "nor.sv:3.1-7.10" *)
module NOR(a, b, y);
  (* src = "nor.sv:3.24-3.25" *)
  input a;
  wire a;
  (* src = "nor.sv:3.39-3.40" *)
  input b;
  wire b;
  (* src = "nor.sv:3.55-3.56" *)
  output y;
  wire y;
  NOR2_X1 _0_ (
    .A1(a),
    .A2(b),
    .ZN(y)
  );
endmodule
