/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "sr_latch.sv:1.1-6.10" *)
module SR_Latch(set, reset, q, q_not);
  (* src = "sr_latch.sv:1.66-1.67" *)
  output q;
  wire q;
  (* src = "sr_latch.sv:1.82-1.87" *)
  output q_not;
  wire q_not;
  (* src = "sr_latch.sv:1.46-1.51" *)
  input reset;
  wire reset;
  (* src = "sr_latch.sv:1.29-1.32" *)
  input set;
  wire set;
  NOR2_X1 _0_ (
    .A1(set),
    .A2(q),
    .ZN(q_not)
  );
  NOR2_X1 _1_ (
    .A1(reset),
    .A2(q_not),
    .ZN(q)
  );
endmodule
