/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "not.sv:3.1-7.10" *)
module NOT(a, y);
  (* src = "not.sv:3.24-3.25" *)
  input a;
  wire a;
  (* src = "not.sv:3.40-3.41" *)
  output y;
  wire y;
  INV_X1 _0_ (
    .A(a),
    .ZN(y)
  );
endmodule
