/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "not.sv:2.1-6.10" *)
module NOT(a, y);
  (* src = "not.sv:2.24-2.25" *)
  input a;
  wire a;
  (* src = "not.sv:2.40-2.41" *)
  output y;
  wire y;
  assign y = ~a;
endmodule
