/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "mux.sv:1.1-5.10" *)
module MUX(in, select, out);
  wire _0_;
  wire _1_;
  (* src = "mux.sv:1.29-1.31" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "mux.sv:1.71-1.74" *)
  output out;
  wire out;
  (* src = "mux.sv:1.50-1.56" *)
  input [1:0] select;
  wire [1:0] select;
  MUX2_X1 _2_ (
    .A(in[2]),
    .B(in[3]),
    .S(select[0]),
    .Z(_0_)
  );
  MUX2_X1 _3_ (
    .A(in[0]),
    .B(in[1]),
    .S(select[0]),
    .Z(_1_)
  );
  MUX2_X1 _4_ (
    .A(_1_),
    .B(_0_),
    .S(select[1]),
    .Z(out)
  );
endmodule
