/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "mux.sv:1.1-13.10" *)
module mux(in0, in1, in2, in3, select, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "mux.sv:1.29-1.32" *)
  input [3:0] in0;
  wire [3:0] in0;
  (* src = "mux.sv:2.30-2.33" *)
  input [3:0] in1;
  wire [3:0] in1;
  (* src = "mux.sv:3.30-3.33" *)
  input [3:0] in2;
  wire [3:0] in2;
  (* src = "mux.sv:4.30-4.33" *)
  input [3:0] in3;
  wire [3:0] in3;
  (* src = "mux.sv:6.31-6.34" *)
  output [3:0] out;
  wire [3:0] out;
  (* src = "mux.sv:5.30-5.36" *)
  input [1:0] select;
  wire [1:0] select;
  INV_X1 _17_ (
    .A(in0[2]),
    .ZN(_00_)
  );
  INV_X1 _18_ (
    .A(in0[1]),
    .ZN(_01_)
  );
  INV_X1 _19_ (
    .A(in0[0]),
    .ZN(_02_)
  );
  INV_X1 _20_ (
    .A(select[0]),
    .ZN(_03_)
  );
  INV_X1 _21_ (
    .A(select[1]),
    .ZN(_04_)
  );
  INV_X1 _22_ (
    .A(in0[3]),
    .ZN(_05_)
  );
  NOR2_X1 _23_ (
    .A1(select[0]),
    .A2(select[1]),
    .ZN(_06_)
  );
  NOR2_X1 _24_ (
    .A1(select[0]),
    .A2(_04_),
    .ZN(_07_)
  );
  XNOR2_X1 _25_ (
    .A(select[0]),
    .B(select[1]),
    .ZN(_08_)
  );
  NAND2_X1 _26_ (
    .A1(in3[2]),
    .A2(_08_),
    .ZN(_09_)
  );
  AOI221_X1 _27_ (
    .A(_06_),
    .B1(_07_),
    .B2(in2[2]),
    .C1(_04_),
    .C2(in1[2]),
    .ZN(_10_)
  );
  AOI22_X1 _28_ (
    .A1(_00_),
    .A2(_06_),
    .B1(_09_),
    .B2(_10_),
    .ZN(out[2])
  );
  OAI21_X1 _29_ (
    .A(_04_),
    .B1(_03_),
    .B2(in1[1]),
    .ZN(_11_)
  );
  AOI22_X1 _30_ (
    .A1(in2[1]),
    .A2(_07_),
    .B1(_08_),
    .B2(in3[1]),
    .ZN(_12_)
  );
  AOI22_X1 _31_ (
    .A1(_01_),
    .A2(_06_),
    .B1(_11_),
    .B2(_12_),
    .ZN(out[1])
  );
  OAI21_X1 _32_ (
    .A(_04_),
    .B1(_03_),
    .B2(in1[0]),
    .ZN(_13_)
  );
  AOI22_X1 _33_ (
    .A1(in2[0]),
    .A2(_07_),
    .B1(_08_),
    .B2(in3[0]),
    .ZN(_14_)
  );
  AOI22_X1 _34_ (
    .A1(_02_),
    .A2(_06_),
    .B1(_13_),
    .B2(_14_),
    .ZN(out[0])
  );
  OAI21_X1 _35_ (
    .A(_04_),
    .B1(in1[3]),
    .B2(_03_),
    .ZN(_15_)
  );
  AOI22_X1 _36_ (
    .A1(in2[3]),
    .A2(_07_),
    .B1(_08_),
    .B2(in3[3]),
    .ZN(_16_)
  );
  AOI22_X1 _37_ (
    .A1(_05_),
    .A2(_06_),
    .B1(_15_),
    .B2(_16_),
    .ZN(out[3])
  );
endmodule
