/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "half_adder.sv:2.1-11.10" *)
module HALF_ADDER(a, b, sum, carry);
  (* src = "half_adder.sv:2.32-2.33" *)
  input a;
  wire a;
  (* src = "half_adder.sv:3.32-3.33" *)
  input b;
  wire b;
  (* src = "half_adder.sv:5.33-5.38" *)
  output carry;
  wire carry;
  (* src = "half_adder.sv:4.33-4.36" *)
  output sum;
  wire sum;
  assign sum = b ^ a;
  assign carry = b & a;
endmodule
