/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "half_adder.sv:1.1-6.10" *)
module half_adder(a, b, sum, carry);
  (* src = "half_adder.sv:1.31-1.32" *)
  input a;
  wire a;
  (* src = "half_adder.sv:1.46-1.47" *)
  input b;
  wire b;
  (* src = "half_adder.sv:1.80-1.85" *)
  output carry;
  wire carry;
  (* src = "half_adder.sv:1.62-1.65" *)
  output sum;
  wire sum;
  AND2_X1 _0_ (
    .A1(a),
    .A2(b),
    .ZN(carry)
  );
  XOR2_X1 _1_ (
    .A(a),
    .B(b),
    .Z(sum)
  );
endmodule
