/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "full_adder.sv:1.1-6.10" *)
module full_adder(a, b, c_in, sum, c_out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "full_adder.sv:1.31-1.32" *)
  input a;
  wire a;
  (* src = "full_adder.sv:1.46-1.47" *)
  input b;
  wire b;
  (* src = "full_adder.sv:1.61-1.65" *)
  input c_in;
  wire c_in;
  (* src = "full_adder.sv:1.98-1.103" *)
  output c_out;
  wire c_out;
  (* src = "full_adder.sv:1.80-1.83" *)
  output sum;
  wire sum;
  INV_X1 _4_ (
    .A(c_in),
    .ZN(_0_)
  );
  NAND2_X1 _5_ (
    .A1(a),
    .A2(b),
    .ZN(_1_)
  );
  NOR2_X1 _6_ (
    .A1(a),
    .A2(b),
    .ZN(_2_)
  );
  XOR2_X1 _7_ (
    .A(a),
    .B(b),
    .Z(_3_)
  );
  OAI21_X1 _8_ (
    .A(_1_),
    .B1(_2_),
    .B2(_0_),
    .ZN(c_out)
  );
  XNOR2_X1 _9_ (
    .A(_0_),
    .B(_3_),
    .ZN(sum)
  );
endmodule
