/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "full_adder.sv:1.1-10.10" *)
module FULL_ADDER(a, b, c_in, sum, c_out);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "full_adder.sv:1.31-1.32" *)
  input a;
  wire a;
  (* src = "full_adder.sv:2.31-2.32" *)
  input b;
  wire b;
  (* src = "full_adder.sv:3.31-3.35" *)
  input c_in;
  wire c_in;
  (* src = "full_adder.sv:5.32-5.37" *)
  output c_out;
  wire c_out;
  (* src = "full_adder.sv:4.32-4.35" *)
  output sum;
  wire sum;
  assign _0_ = ~(b ^ a);
  assign sum = ~(_0_ ^ c_in);
  assign _1_ = b & a;
  assign _2_ = c_in & ~(_0_);
  assign c_out = _2_ | _1_;
endmodule
