/*
Quite often your logic needs to react to a change on some control signal. That can be an external input, 
something saying that another part of the circuit has done it's job and that it is safe to continue. All 
sorts of scenarios exist that call for a signal generated by one part of a system to be detected by another 
part or a different system.

Implement a sticky edge detector (or a edge capture) circuit which captures any neg-edge (from 1-0) transition 
on a 32-bit input signal. The edge detection and capture must be performed on per bit basis for all the 32-bits 
of the input. All the flops should be positive edge triggered with asynchronous resets (if any).

Interface Requirements

- The detection should be sticky - once neg-edge is detected on any bit of the input, the particular bit in the `edge_o` 
should remain asserted until reset is seen
- The module should produce the output on every cycle
*/

module edge_capture(
    input logic clk,
    input logic reset,
    input logic[31:0] data_i,
    output logic[31:0] edge_o
);

    logic[31:0] data_q;         // Save previous data_in
    logic[31:0] edge_q;         // Save previous edge_o
    logic[31:0] negedge_det;    // Determine if negative edge detected

    always_ff @(posedge clk or posedge reset)
        if (reset) begin
            data_q <= 32'h0;
            edge_q <= 32'h0;
        end else begin
            data_q <= data_i[31:0];
            edge_q <= edge_o[31:0];
        end
    
    assign negedge_det = ~data_i[31:0] & data_q[31:0];
    assign edge_o = negedge_det[31:0] | edge_q[31:0];

endmodule
