/*
Quite often your logic needs to react to a change on some control signal. That can be an external input, something saying 
that another part of the circuit has done it's job and that it is safe to continue. All sorts of scenarios exist that call 
for a signal generated by one part of a system to be detected by another part or a different system.

Implement a one-shot circuit which detects a pos-edge (from 0-1) change on the input. All the flops (if any) should be positive 
edge triggered with asynchronous resets.

Interface Requirements

- The output should go high for one cycle only when pos-edge is detected on the input
- The module should produce the output on every cycle
*/

module one_shot(
    input logic clk,
    input logic reset,
    input logic data_i,
    output logic shot_o
);

    logic data_q;   // Hold value of data_i from previous cycle

    always_ff @(posedge clk or posedge reset)
        if (reset)
            data_q <= 1'b0;
        else
            data_q <= data_i;
    
    assign shot_o = data_i & ~data_q;

endmodule