/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "sr_latch.sv:1.1-6.10" *)
module SR_Latch(set, reset, q, q_not);
  wire _0_;
  wire _1_;
  (* src = "sr_latch.sv:1.66-1.67" *)
  output q;
  wire q;
  (* src = "sr_latch.sv:1.82-1.87" *)
  output q_not;
  wire q_not;
  (* src = "sr_latch.sv:1.46-1.51" *)
  input reset;
  wire reset;
  (* src = "sr_latch.sv:1.29-1.32" *)
  input set;
  wire set;
  INV_X1 _2_ (
    .A(set),
    .ZN(_0_)
  );
  INV_X1 _3_ (
    .A(q),
    .ZN(_1_)
  );
  OR2_X1 _4_ (
    .A1(reset),
    .A2(_1_),
    .ZN(q_not)
  );
  OAI21_X1 _5_ (
    .A(_0_),
    .B1(reset),
    .B2(_1_),
    .ZN(q)
  );
endmodule
