/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "or.sv:2.1-6.10" *)
module OR(a, b, y);
  (* src = "or.sv:2.23-2.24" *)
  input a;
  wire a;
  (* src = "or.sv:2.38-2.39" *)
  input b;
  wire b;
  (* src = "or.sv:2.54-2.55" *)
  output y;
  wire y;
  OR2_X1 _0_ (
    .A1(a),
    .A2(b),
    .ZN(y)
  );
endmodule
