/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "xnor.sv:2.1-6.10" *)
module XNOR(a, b, y);
  (* src = "xnor.sv:2.25-2.26" *)
  input a;
  wire a;
  (* src = "xnor.sv:2.40-2.41" *)
  input b;
  wire b;
  (* src = "xnor.sv:2.56-2.57" *)
  output y;
  wire y;
  XNOR2_X1 _0_ (
    .A(a),
    .B(b),
    .ZN(y)
  );
endmodule
