/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "sr_latch.sv:1.1-6.10" *)
module SR_Latch(set, reset, q, q_not);
  (* src = "sr_latch.sv:1.66-1.67" *)
  output q;
  wire q;
  (* src = "sr_latch.sv:1.82-1.87" *)
  output q_not;
  wire q_not;
  (* src = "sr_latch.sv:1.46-1.51" *)
  input reset;
  wire reset;
  (* src = "sr_latch.sv:1.29-1.32" *)
  input set;
  wire set;
  assign q_not = ~(q | set);
  assign q = ~(q_not | reset);
endmodule
