/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "xor.sv:3.1-7.10" *)
module XOR(a, b, y);
  (* src = "xor.sv:3.24-3.25" *)
  input a;
  wire a;
  (* src = "xor.sv:3.39-3.40" *)
  input b;
  wire b;
  (* src = "xor.sv:3.55-3.56" *)
  output y;
  wire y;
  XOR2_X1 _0_ (
    .A(a),
    .B(b),
    .Z(y)
  );
endmodule
