/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "and.sv:2.1-6.10" *)
module AND(a, b, y);
  (* src = "and.sv:2.24-2.25" *)
  input a;
  wire a;
  (* src = "and.sv:2.39-2.40" *)
  input b;
  wire b;
  (* src = "and.sv:2.55-2.56" *)
  output y;
  wire y;
  AND2_X1 _0_ (
    .A1(a),
    .A2(b),
    .ZN(y)
  );
endmodule
