/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "and.sv:2.1-6.10" *)
module AND(a, b, y);
  (* src = "and.sv:2.24-2.25" *)
  input a;
  wire a;
  (* src = "and.sv:2.39-2.40" *)
  input b;
  wire b;
  (* src = "and.sv:2.55-2.56" *)
  output y;
  wire y;
  assign y = b & a;
endmodule
