/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "mux2.sv:1.1-13.10" *)
module MUX2(in0, in1, in2, in3, select, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "mux2.sv:1.30-1.33" *)
  input [3:0] in0;
  wire [3:0] in0;
  (* src = "mux2.sv:2.30-2.33" *)
  input [3:0] in1;
  wire [3:0] in1;
  (* src = "mux2.sv:3.30-3.33" *)
  input [3:0] in2;
  wire [3:0] in2;
  (* src = "mux2.sv:4.30-4.33" *)
  input [3:0] in3;
  wire [3:0] in3;
  (* src = "mux2.sv:6.31-6.34" *)
  output [3:0] out;
  wire [3:0] out;
  (* src = "mux2.sv:5.30-5.36" *)
  input [1:0] select;
  wire [1:0] select;
  assign _00_ = ~(select[0] | select[1]);
  assign _01_ = select[0] & ~(select[1]);
  assign _02_ = select[1] & ~(select[0]);
  assign _03_ = _02_ ? in2[0] : in3[0];
  assign _04_ = _01_ ? in1[0] : _03_;
  assign out[0] = _00_ ? in0[0] : _04_;
  assign _05_ = _02_ ? in2[1] : in3[1];
  assign _06_ = _01_ ? in1[1] : _05_;
  assign out[1] = _00_ ? in0[1] : _06_;
  assign _07_ = _02_ ? in2[2] : in3[2];
  assign _08_ = _01_ ? in1[2] : _07_;
  assign out[2] = _00_ ? in0[2] : _08_;
  assign _09_ = _02_ ? in2[3] : in3[3];
  assign _10_ = _01_ ? in1[3] : _09_;
  assign out[3] = _00_ ? in0[3] : _10_;
endmodule
