/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "mux.sv:1.1-5.10" *)
module MUX(in, select, out);
  wire _0_;
  wire _1_;
  (* src = "mux.sv:1.29-1.31" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "mux.sv:1.71-1.74" *)
  output out;
  wire out;
  (* src = "mux.sv:1.50-1.56" *)
  input [1:0] select;
  wire [1:0] select;
  assign _0_ = select[0] ? in[1] : in[0];
  assign _1_ = select[0] ? in[3] : in[2];
  assign out = select[1] ? _1_ : _0_;
endmodule
