/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 16.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "dff_async_reset.sv:1.1-9.10" *)
module dff_async_reset(d, clk, reset_n, q);
  wire _0_;
  (* src = "dff_async_reset.sv:1.51-1.54" *)
  input clk;
  wire clk;
  (* src = "dff_async_reset.sv:1.36-1.37" *)
  input d;
  wire d;
  (* src = "dff_async_reset.sv:1.90-1.91" *)
  output q;
  wire q;
  (* src = "dff_async_reset.sv:1.68-1.75" *)
  input reset_n;
  wire reset_n;
  (* src = "dff_async_reset.sv:3.1-7.16" *)
  DFFR_X1 _1_ (
    .CK(clk),
    .D(d),
    .Q(q),
    .QN(_0_),
    .RN(reset_n)
  );
endmodule
